parameters:
  - name: rgLocation
    type: string
    default: 'South Africa North'
  - name: deploymentMode
    type: string
    default: 'Incremental'
  - name: dependsOn
    type: object
    default: []

stages:
- stage: DeployAzureSQLFireWallRules
  displayName: 'Deploy Azure SQL Firewall Rules'
  dependsOn: ${{ parameters.dependsOn }}
  variables:
    allowedSQLServerIPs: dependencies.DeployContainerApps.DeployContainerApps.outputs.containerAppOutboundIpAddress
  jobs:
  - job: DeployAzureSQLFirewallRules
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Deploy Azure SQL Firewall Rules'
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: $(serviceConnectionName)
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(resourceGroupName)
        location: ${{ parameters.rgLocation }}
        templateLocation: 'Linked artifact'
        csmFile: '$(Pipeline.Workspace)/s/infra-as-code/azure-sql-firewall-rules/main.bicep'
        deploymentMode: ${{ parameters.deploymentMode }}
        overrideParameters: >-
          -serverName $(databaseServerName)
          -allowedIPs $(allowedSQLServerIPs)