parameters:
  - name: deploymentMode
    type: string
    default: 'Incremental'
  - name: rgLocation
    type: string
    default: 'South Africa North'

stages:
- stage: CreateOrUpdateAzureContainerRegistry
  displayName: 'Create or Update Azure Container Registry'
  jobs:
  - job: UpsertAzureContainerRegistry
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Create or Update Azure Container Registry'
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: $(serviceConnectionName)
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(resourceGroupName)
        location: ${{ parameters.rgLocation }}
        templateLocation: 'Linked artifact'
        csmFile: '$(Pipeline.Workspace)/s/infra-as-code/container-registry/main.bicep'
        deploymentMode: ${{ parameters.deploymentMode }}
        overrideParameters: >-
          -registryName $(registryName)
          -principalId $(servicePrincipleId)
          -registrySku $(registrySku)
