parameters:
  - name: deploymentMode
    type: string
    default: 'Incremental'
  - name: rgLocation
    type: string
    default: 'South Africa North'
  - name: dependsOn
    type: object
    default: []
  - name: databaseConnectionString
    type: string
    default: ''

# Add A Key Vault For Some Of these env variables
stages:
- stage: DeployContainerApps
  displayName: 'Deploy Container Apps'
  dependsOn: ${{ parameters.dependsOn }}
  jobs:
  - job: DeployContainerApps
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Deploy Container Apps'
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: $(serviceConnectionName)
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(resourceGroupName)
        location: ${{ parameters.rgLocation }}
        templateLocation: 'Linked artifact'
        csmFile: '$(Pipeline.Workspace)/s/infra-as-code/container-apps/main.bicep'
        deploymentMode: ${{ parameters.deploymentMode }}
        overrideParameters: >-
          -containerRegistryName $(registryName)
          -containerAppsEnvironmentName $(containerAppsEnvironmentName)
          -managedIdentityName $(managedIdentityName)
          -webApiContainerAppName $(webApiContainerAppName)
          -webApiImage $(webApiImageName)
          -webApiTargetPort $(webApiPort)
          -webApiCpu $(cpuCores)
          -webApiMemory $(memoryInGb)
          -webApiEnvironmentVariables [{ "name": "ASPNETCORE_ENVIRONMENT", "value": "Production" }]
          -sqlServerName $(databaseServerName)
          -sqlDBName $(databaseName)