trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
- template: ./variables/variables.yml

stages:
# - template: ./templates/stages/deploy-azure-registry.yml
#   parameters:
#     deploymentMode: ${{ variables.deploymentMode }}
#     rgLocation: ${{ variables.location }}

# - template: ./templates/stages/build-and-push-images.yml
#   parameters:
#     clientImageName: ${{ variables.clientImageName }}
#     webApiImageName: ${{ variables.webApiImageName }}
#     arcName: ${{ variables.registryName }}
#     dependsOn:
#       - CreateOrUpdateAzureContainerRegistry

- template: ./templates/stages/deploy-azure-container-apps.yml
  parameters:
    deploymentMode: ${{ variables.deploymentMode }}
    rgLocation: ${{ variables.location }}
    # dependsOn:
    #   - BuildAndDeployImages

- template: ./templates/stages/deploy-azure-sql.yml
  parameters:
    dependsOn:
      - DeployContainerApps

- template: ./templates/stages/deploy-azure-sql-firewall-rules.yml
  parameters:
    dependsOn:
      - DeployAzureSQL
