trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
- template: ./variables/variables.yml

stages:
- template: ./templates/stages/deploy-azure-registry.yml
  parameters:
    deploymentMode: ${{ variables.deploymentMode }}
    rgLocation: ${{ variables.location }}

- template: ./templates/stages/build-and-push-images.yml
  parameters:
    postgresImageName: ${{ variables.postgresImageName }}
    clientImageName: ${{ variables.clientImageName }}
    webApiImageName: ${{ variables.webApiImageName }}
    nginxImageName: ${{ variables.nginxImageName }}
    arcName: ${{ variables.registryName }}
    dependsOn:
      - CreateOrUpdateAzureContainerRegistry
