# Create Cart Item
# @name createCartItemCall
POST {{HostAddress}}/api/cart HTTP/1.1
content-type: application/json

{
    "Name": "Test Cart Item - {{$guid}}",
    "Description": "Test Cart Item Description",
    "GroceryItems": []
}

###

@createCartId = {{createCartItemCall.response.body.$.data.cartId}}

# Get Cart Item
# @name getCartItemCall
GET {{HostAddress}}/api/cart/{{createCartId}} HTTP/1.1

###

# Update Cart
# @name updateCartItemCall
PUT {{HostAddress}}/api/cart/{{createCartId}} HTTP/1.1
Content-Type: application/json

{
    "Id": "{{createCartId}}",
    "Name": "Test Cart Item - {{createCartId}}",
    "Description": "Test Cart Item Description",
    "GroceryItems": [{
        "Name": "Test Grocery Item - {{createCartId}}",
        "Description": "Test Grocery Item Description",
        "Quantity": 1,
        "Price": 1.99,
        "Category": "Test Category"
    }]
}
###

# Delete Cart Item
# @name deleteCartItemCall
DELETE {{HostAddress}}/api/cart/{{createCartId}} HTTP/1.1
###

# Get All Cart Item
# @name getAllCartItems
GET {{HostAddress}}/api/cart/all HTTP/1.1
###

