FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /source/groceries-web-api

#restore app solution
COPY *.sln .
COPY ./Groceries.Core.Domain/*.csproj ./Groceries.Core.Domain/
COPY ./Groceries.Core.Application/*.csproj ./Groceries.Core.Application/
COPY ./Groceries.Infrastructure/*.csproj ./Groceries.Infrastructure/
COPY ./Groceries.Data/*.csproj ./Groceries.Data/
COPY ./Groceries.Tests.Unit/*.csproj ./Groceries.Tests.Unit/
COPY ./Groceries.Tests.Integration/*.csproj ./Groceries.Tests.Integration/

RUN dotnet restore

# add unit tests to image build?

#copy all files to source and publish
COPY . ../groceries-web-api/
WORKDIR /source/groceries-web-api
RUN dotnet publish -c release -o /app --no-restore

#build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "groceries-web-api.dll"]
