services:
  # postgres:
  #   image: postgres:latest
  #   environment:
  #     POSTGERS_PASSWORD: postgres_password # required for postgress
  client:
    build:
      context: ./groceries-web
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
  webapi:
    build:
      context: ./groceries-web-api
      dockerfile: Dockerfile.dev
    ports: 
      - '7005:5000'
    #using defaults for initial set-up
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - DOTNET_RUNNING_IN_CONTAINER=true
      - PGUSER=postgres
      - PGPASSWORD=postgres_password
      - PGDB=postgres # to change the database name
      - PGHOST=postgres
      - PGPORT=5432 # default port
