services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile.dev
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres_password # required for postgress
      POSTGRES_DB: groceries_database
    restart: unless-stopped
  client:
    build:
      context: ./groceries-web
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./groceries-web:/app
    ports:
      - '3000:3000'
    restart: on-failure
    environment:
      - WDS_SOCKET_PORT=0
  webapi: 
    build:
      context: ./groceries-web-api
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres
    ports: 
      - '7005:5000'
    restart: on-failure
    #using defaults for initial set-up
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true
      - PGUSER=postgres
      - PGPASSWORD=postgres_password
      - PGDB=groceries_database
      - PGHOST=postgres
      - PGPORT=5432 # default port
